version: "3"

services:
    backend:
        build:
            context: .
            dockerfile: test_from_stori_card/Dockerfile
        container_name: back
        volumes:
            - .:/app/
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - backend

    db:
        image: postgres:12
        container_name: db
        environment:
            - POSTGRES_DB=storidb
            - POSTGRES_USER=dbadmin
            - POSTGRES_PASSWORD=stori123456789
        volumes:
            - pg-data:/var/lib/postgresql/data/
            - ./db:/docker-entrypoint-initdb.d/
        ports:
            - "5435:5432"
        networks:
            - backend

volumes:
    pg-data:
        driver: local

networks:
    backend:
        driver: bridge
