# Generated by Django 5.0.2 on 2024-03-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('transaction', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
